export enum StatutReservationWorkflow {
    PAS_CONTACTE = 'PAS_CONTACTE',
    CONTACT_PRIS = 'CONTACT_PRIS',
    DISCUSSION_EN_COURS = 'DISCUSSION_EN_COURS',
    SERA_ABSENT = 'SERA_ABSENT',
    CONSIDERE_ABSENT = 'CONSIDERE_ABSENT',
    PRESENT = 'PRESENT',
    FACTURE = 'FACTURE',
    PAIEMENT_RECU = 'PAIEMENT_RECU',
    PAIEMENT_EN_RETARD = 'PAIEMENT_EN_RETARD'
}
